name: Test this action

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: debug logging
      run: |
        echo ${{ github.event.ref }}
        echo $GITHUB_REF
        echo github.event.ref
        echo ${{ github.pull_request.title }}
        echo ${{ github.pull_request.head.ref }}
        
    - name: Test Slack action
      if: startsWith(github.event.ref, 'feature/startsWith')
      uses: frankkienl/ga-pr-slack-notify@master
      with:
        webhook: ${{ secrets.slack_webhook }}
