name: Test this action

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test Slack action
      uses: frankkienl/ga-pr-slack-notify@master
      with:
        webhook: ${{ secrets.slack_webhook }}
